name: Verify Pull Request
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  reused-verify:
    uses: ahlsell-group/api-toolkit/.github/workflows/verify-pr.yml@master
    secrets: inherit
  verify:
    name: Verify PR
    runs-on: ubuntu-latest
    needs: reused-verify
    steps:
      - run: echo 'verified'
